CREATE TABLE [Advanced] (
  [ID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Dive_ID] LONG ,
  [Depth_1] DOUBLE ,
  [Depth_1_Unit_ID] LONG ,
  [Depth_2] DOUBLE ,
  [Depth_2_Unit_ID] LONG ,
  [Depth_3] DOUBLE ,
  [Depth_3_Unit_ID] LONG ,
  [Pressure_1_Start] DOUBLE ,
  [Pressure_1_Start_Unit_ID] LONG ,
  [Pressure_1_End] DOUBLE ,
  [Pressure_1_End_Unit_ID] LONG ,
  [EANx_1] DOUBLE ,
  [Tank_1_Size] DOUBLE ,
  [Tank_1_Size_Unit_ID] LONG ,
  [Tank_1_Type] VARCHAR (255),
  [Pressure_2_Start] DOUBLE ,
  [Pressure_2_Start_Unit_ID] LONG ,
  [Pressure_2_End] DOUBLE ,
  [Pressure_2_End_Unit_ID] LONG ,
  [O2] DOUBLE ,
  [Tank_2_Size] DOUBLE ,
  [Tank_2_Size_Unit_ID] LONG ,
  [Tank_2_Type] VARCHAR (255),
  [Pressure_3_Start] DOUBLE ,
  [Pressure_3_Start_Unit_ID] LONG ,
  [Pressure_3_End] DOUBLE ,
  [Pressure_3_End_Unit_ID] LONG ,
  [EANx_2] DOUBLE ,
  [Scrubber_Start] DOUBLE ,
  [Scrubber_Used] DOUBLE ,
  [Scrubber_Remaining] DOUBLE ,
  [Tank_3_Size] DOUBLE ,
  [Tank_3_Size_Unit_ID] LONG ,
  [Tank_3_Type] VARCHAR (255)
)
