CREATE TABLE [Details] (
  [ID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Dive_ID] LONG ,
  [Waves] BIT ,
  [Freshwater] BIT ,
  [Saltwater] BIT ,
  [Shore] BIT ,
  [Boat] BIT ,
  [Current] BIT ,
  [Computer] BIT ,
  [Table] BIT ,
  [Drift] BIT ,
  [Night] BIT ,
  [Training] BIT ,
  [Emergency] BIT ,
  [Surf] BIT ,
  [Wreck] BIT ,
  [Cave] BIT ,
  [Cavern] BIT ,
  [Surge] BIT ,
  [Scooter] BIT ,
  [Camera] BIT ,
  [Deep] BIT ,
  [Guided] BIT ,
  [Hunt] BIT ,
  [Ice] BIT ,
  [Nature] BIT ,
  [Navigation] BIT ,
  [Nitrox] BIT ,
  [Photo] BIT ,
  [Video] BIT ,
  [Resuce] BIT ,
  [River] BIT ,
  [Search_Recover] BIT ,
  [Tech] BIT ,
  [Instruction] BIT ,
  [Rebreather] BIT ,
  [Altitude] BIT ,
  [Recreation] BIT 
)
