dbMemo "SQL" ="SELECT Get_Later_Dives_In.ID, Get_Later_Dives_In.Time_In, Get_Earlier_Dives_Out."
    "Time_Out, DateDiff(\"n\",Get_Earlier_Dives_Out.Time_Out,Get_Later_Dives_In.Time_"
    "In) AS Surface_Interval, IIf(Surface_Interval>1440,Null,Surface_Interval) AS Sur"
    "face_Interval_Adjusted, Nz( Surface_Interval_Adjusted,\"N/A\") AS Surface_Interv"
    "al_Adjusted2\015\012FROM Get_Later_Dives_In LEFT JOIN Get_Earlier_Dives_Out ON G"
    "et_Later_Dives_In.RowNum = Get_Earlier_Dives_Out.RowNum;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
