dbMemo "SQL" ="SELECT d.ID, d.Time_Out, (SELECT COUNT(*) FROM Dives WHERE d.ID>=ID) AS RowNum\015"
    "\012FROM Dives AS d\015\012WHERE d.Time_Out <(SELECT Max(sub2.Time_Out) from Div"
    "es sub2)\015\012ORDER BY d.Time_Out;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
